# config.yaml
streamers:
  # 提示：Youtube_channel_id 可通过 yt-dlp --print channel_id [视频链接] 获取
  # 目前支持平台: youtube, twitch, twitcast, twitter(x)
  - name: "Yuka"
    accounts:
      - platform: "youtube"
        channel_id: "UCdvq5i3RyRsoTqITD1xSxNw"

      - platform: "twitch"
        channel_name: "柊優花 (hiiragiyukaofficial)"

      - platform: "twitter"
        channel_name: "@hiiragi_yuka530"
        
  - name: "Haru"
    accounts:
      - platform: "youtube"
        channel_id: "UCrOV-crqUmRluPVOjjVs-Xw"

      - platform: "twitcast"
        channel_name: "shino_nome22"

whisper:
  language: "ja"
  model: "large-v3-turbo"
  compute_type: "float16"
  beam_size: 5
  vad_filter: True
  condition_on_previous_text: False
  no_speech_threshold: 0.5
  vad_threshold: 0.35
  vad_min_speech_duration_ms: 250

prompts:
  # 路径相对于项目根目录
  speech_analyze: "src/highlight_cliper/prompt/speech_analyze.md"
  to_excel: "src/highlight_cliper/prompt/to_excel.md"

tools_paths:
  # 注意：程序会自动在以下路径前加上 /tools/ 文件夹名
  yt_dlp: "yt-dlp/yt-dlp.exe"
  twitch_downloader_cli: "TwitchDownloaderCLI/TwitchDownloaderCLI.exe"
  ffmpeg: "ffmpeg-8.0.1-essentials_build/bin/ffmpeg.exe"
  ffprobe: "ffmpeg-8.0.1-essentials_build/bin/ffprobe.exe"
  node: "node-v24.13.1-win-x64/node.exe"
  npm: "node-v24.13.1-win-x64/npm.cmd"
  faster_whisper: "Faster-Whisper-XXL/faster-whisper-xxl.exe"